# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preceptor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='formulario2',
            name='preceptor',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preceptor',
            name='apellido',
            field=models.CharField(default=-2016, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preceptor',
            name='nombre_usuario',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
