# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0006_alumno_preceptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='preceptor',
        ),
        migrations.AddField(
            model_name='alumno',
            name='preceptor',
            field=models.ManyToManyField(to='adi.Preceptor'),
        ),
    ]
