# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0007_auto_20170804_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='preceptor',
        ),
        migrations.AddField(
            model_name='preceptor',
            name='alumno',
            field=models.ForeignKey(default=-2011, on_delete=django.db.models.deletion.CASCADE, to='adi.Alumno'),
            preserve_default=False,
        ),
    ]
