# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0005_auto_20170731_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='preceptor',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='adi.Preceptor'),
            preserve_default=False,
        ),
    ]
