# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0010_alumno_preceptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
