# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0011_alumno_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=1)),
                ('division', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='preceptor',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='adi.Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preceptor',
            name='curso',
            field=models.ForeignKey(default=-2000, on_delete=django.db.models.deletion.CASCADE, to='adi.Curso'),
            preserve_default=False,
        ),
    ]
