# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0012_auto_20170814_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
