# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0015_auto_20170815_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario2',
            old_name='alumnos',
            new_name='alumno',
        ),
    ]
