# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0018_formulario3_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='faltas',
            field=models.FloatField(default=543),
            preserve_default=False,
        ),
    ]
