# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0019_alumno_faltas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario2',
            name='estado',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='formulario3',
            name='estado',
            field=models.CharField(max_length=11),
        ),
    ]
