# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0022_auto_20170829_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
