# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0026_auto_20170830_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preceptor',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='preceptor',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, to='adi.Preceptor'),
            preserve_default=False,
        ),
    ]
