# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0027_auto_20170831_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(max_length=11)),
                ('tipo', models.BooleanField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adi.Alumno')),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adi.Preceptor')),
            ],
        ),
        migrations.RemoveField(
            model_name='formulario2',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='formulario2',
            name='preceptor',
        ),
        migrations.RemoveField(
            model_name='formulario3',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='formulario3',
            name='preceptor',
        ),
        migrations.DeleteModel(
            name='Formulario2',
        ),
        migrations.DeleteModel(
            name='Formulario3',
        ),
    ]
