# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0028_auto_20170906_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='padre_tutor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='preceptor',
            name='id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='id',
            field=models.AutoField(auto_created=True, default=432, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='padre_tutor',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preceptor',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
