# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0029_auto_20170914_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='padre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adi.Padre_Tutor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='padre_tutor',
            name='apellido',
            field=models.CharField(default=43, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='padre_tutor',
            name='id',
            field=models.AutoField(auto_created=True, default=1982, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='padre_tutor',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
